plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/kleansoze/Desktop/Exec Assit/projects/finance/sports-betting/sporty-dashboard"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]